### ISSUE TITLE
CMV WAB Widget Query - Result panel options Feature Action doesn't work

### ISSUE THREAD

**Issue by mayur9785** [cmv/cmv-wab-widgets#19]
HI,

I added query WAB widget in app and it is working.  After querying, in Results panel if I click on  Feature Action button, the menu doesn't display 

![1](https://user-images.githubusercontent.com/6058868/29363018-ea5d0dbc-8296-11e7-847e-45ce8d33906c.PNG)

**Comment by tmcgee** [comment]
This error appears to occur in a Flash "action" and the error is due to the map not being set for this "action". It appears the map is set by responding to a particular topic being published. Perhaps something like:

``` javascript
topic.publish('mapLoaded', this.map);
```

I will look into adding this to the `_WABMixin`. At this point, I am not sure when that might occur.
